# Generated by Django 3.2.4 on 2024-05-04 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistgooglecalendar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleavailability',
            name='therapist',
            field=models.ForeignKey(limit_choices_to={'is_therapist': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='therapist',
            field=models.ForeignKey(limit_choices_to={'is_therapist': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Therapist'),
        ),
        migrations.AddField(
            model_name='event',
            name='therapist',
            field=models.ForeignKey(limit_choices_to={'is_therapist': True}, on_delete=django.db.models.deletion.CASCADE, related_name='events_scheduled', to=settings.AUTH_USER_MODEL, verbose_name='Therapist'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleavailability',
            unique_together={('therapist', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
